# This config file is to setup ucas-ctf.github.io.
title: UCAS CTF

# switch to kramdown for correct GFM markdown
# with support for HTML tags like details and summary.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: false

# math:
#   katex:
#     css: 'css/math/katex.min.css'
#     options:
#       throwOnError: false
#   mathjax:
#     css: 'css/math/style.css'
#     options:
#       conversion:
#         display: false
#       tex:
#       svg:

mathjax:
  tags: none # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to pages rendered by MathJax
  every_page: true # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter
  packages: # extra packages to load
  extension_options: {}
    # you can put your extension options here
    # see http://docs.mathjax.org/en/latest/options/input/tex.html#tex-extension-options for more detail
