# This config file is to setup ucas-ctf.github.io.
title: UCAS CTF

# switch to kramdown for correct GFM markdown
# with support for HTML tags like details and summary.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: false

math:
  katex:
    css: 'css/math/katex.min.css'
    options:
      throwOnError: false
  mathjax:
    css: 'css/math/style.css'
    options:
      conversion:
        display: false
      tex:
      svg:
